### PR TITLE
fix policy uploading to defined partition

### LINKED ISSUE #135: allow uploading policies to a specific partition
Currently, the ltm_policy resource does not have the ability to upload policies to a partition which is not Common.

### PR DESCRIPTION
**Pull request by jlosito**
This pull request allows one to upload policies to specific partitions.

Here's some example code that I used to test it.

```hcl
resource "bigip_ltm_policy" "my_test_policy" {
  name = "my_test_policy"
  strategy = "/Common/best-match"
  partition = "Terraform"
  requires = ["https"]
  published_copy = "/Terraform/Drafts/my_test_policy"
  controls = ["forwarding"]
  rule {
    name = "my_test_rule"

    condition {
      http_uri = true
      path = true
      starts_with = true
      values = [ "/api/" ]
      request = true
    }   

    action {
      forward = true
      pool = "/Terraform/my_test_pool"
      request = true
    }   
  }
}
```

fixes #135

### CODE REVIEW

**Comment by jlosito** [comment]
Hey @dannyk81 want to test this? This change worked for me.

**Comment by jlosito** [comment]
Hey @scshitole. This seems to be working for me. I had to make changes to the rest client as well. Are we building those as well? 

```
jlosito$ git remote -v
origin	git@github.com:jlosito/terraform-provider-bigip.git (fetch)
origin	git@github.com:jlosito/terraform-provider-bigip.git (push)
jlosito$ git checkout pr
Already on 'pr'
Your branch is up to date with 'origin/pr'.
jlosito$ pwd
/Users/jlosito/gopath/src/github.com/terraform-providers/terraform-provider-bigip
jlosito$ make build
==> Checking that code complies with gofmt requirements...
go install
jlosito$ make tools
GO111MODULE=off go get -u github.com/alecthomas/gometalinter
GO111MODULE=off gometalinter --install
Installing:
  deadcode
  dupl
  errcheck
  gochecknoglobals
  gochecknoinits
  goconst
  gocyclo
  goimports
  golint
  gosec
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  varcheck
ls $GOPATH/bin
deadcode                 gochecknoinits           golint                   ineffassign              misspell                 structcheck              varcheck
dupl                     goconst                  gometalinter             interfacer               nakedret                 terraform-provider-bigip
errcheck                 gocyclo                  gosec                    lll                      safesql                  unconvert
gochecknoglobals         goimports                gotype                   maligned                 staticcheck              unparam

```

**Comment by scshitole** [comment]
@jlosito  do we need  method CreatePolicyDraft in https://github.com/f5devcentral/go-bigip/blob/master/ltm.go .  ?

**Comment by jlosito** [comment]
@scshitole Yes. I added it right [here](https://github.com/terraform-providers/terraform-provider-bigip/pull/141/files#diff-33489523f52a01c4d5d331c1a2eb7d13R2626-R2634). What confused me about this is it looks like the terraform-provider-bigip project isn't pulling the dependencies at build time since all of them were committed under the vendor directory of this project. For example, the F5 rest client was committed [here](https://github.com/terraform-providers/terraform-provider-bigip/tree/master/vendor/github.com/f5devcentral/go-bigip) which is under this project, so it kind of threw me off where I should make the change. So we remove the vendor directory from this project and add it to the [.gitingore](https://github.com/terraform-providers/terraform-provider-bigip/blob/master/.gitignore)?

**Comment by scshitole** [comment]
Thanks, Can you please create a PR for the same at
https://github.com/f5devcentral/go-bigip  as we always update the Vendor
using GO Modules

**Comment by jlosito** [comment]
@scshitole Do we submit tickets for the F5 rest client here too? I don't see the ability to create a ticket under that project.

**Comment by dannyk81** [comment]
the go-bigip library repo is a fork without issue tracking, which is indeed a challenge when contributing to this provider...

I requested to do a hard fork for the go-bigip repo a while back and allow issues tracking, as well as build tests and a proper CI process.

https://github.com/terraform-providers/terraform-provider-bigip/issues/89

**Comment by jlosito** [comment]
@scshitole is there anything I have to do on my end now that the rest client portion has been merged into the master branch of the go-bigip project? This PR would be a game changer for my organization. Therefore, I'd willing to create another PR with the required changes if necessary.

**Comment by dannyk81** [comment]
@jlosito was this PR reverted because it was missing the merge in go-bigip? in that case I suggest you resubmit the PR and update the vendoring to pull in the latest go-bigip (in case it's not updated here in master already)

**Comment by jlosito** [comment]
Hey @dannyk81. Yes you are correct. I'll resubmit another PR with the updates. Thanks for the help.

**Pull request merged**
