### PR TITLE
updated travis file

### PR DESCRIPTION
**Pull request by scshitole**

### CODE REVIEW

**Comment by scshitole** [comment]
@dannyk81 I did ran make fmt and go fmt
make fmt
==> Fixing source code with gofmt...
gofmt -s -w ./bigip
SJC-ML-00028512:terraform-provider-bigip shitole$ git status
On branch dev-branch
Your branch is up to date with 'origin/dev-branch'.

nothing to commit, working tree clean

**Comment by dannyk81** [comment]
```
dannyk ~/work/gocode/src/github.com/terraform-providers/terraform-provider-bigip/bigip $ git checkout dev-branch
Switched to branch 'dev-branch'
Your branch is up to date with 'origin/dev-branch'.
dannyk ~/work/gocode/src/github.com/terraform-providers/terraform-provider-bigip/bigip $ go fmt *
resource_bigip_ltm_virtual_server.go
resource_bigip_sys_snmp_traps.go
dannyk ~/work/gocode/src/github.com/terraform-providers/terraform-provider-bigip/bigip $ git status
On branch dev-branch
Your branch is up to date with 'origin/dev-branch'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   resource_bigip_ltm_virtual_server.go
        modified:   resource_bigip_sys_snmp_traps.go

no changes added to commit (use "git add" and/or "git commit -a")
```

```
dannyk ~/work/gocode/src/github.com/terraform-providers/terraform-provider-bigip $ gofmt -s -w ./bigip/
dannyk ~/work/gocode/src/github.com/terraform-providers/terraform-provider-bigip $ git status
On branch dev-branch
Your branch is up to date with 'origin/dev-branch'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bigip/resource_bigip_ltm_virtual_server.go
        modified:   bigip/resource_bigip_sys_snmp_traps.go

no changes added to commit (use "git add" and/or "git commit -a")
```

Something seems screwed up on your local branch...

**Comment by scshitole** [comment]
@dannyk81 
git status
On branch dev-branch
Your branch is up to date with 'origin/dev-branch'.

nothing to commit, working tree clean
SJC-ML-00028512:terraform-provider-bigip shitole$ 
SJC-ML-00028512:terraform-provider-bigip shitole$ 
SJC-ML-00028512:terraform-provider-bigip shitole$ pwd
/Users/shitole/top/src/github.com/terraform-providers/terraform-provider-bigip
SJC-ML-00028512:terraform-provider-bigip shitole$ cd bigip/
SJC-ML-00028512:bigip shitole$ go fmt *
SJC-ML-00028512:bigip shitole$ git status
On branch dev-branch
Your branch is up to date with 'origin/dev-branch'.

nothing to commit, working tree clean
SJC-ML-00028512:bigip shitole$

**Comment by dannyk81** [comment]
well, we can keep exchanging outputs 😄 

But, if you do a clean `git clone` for `master` and/or `dev-branch` and run `go fmt *` in `bigip` folder you should see that two files are missing formatting.

**Comment by dannyk81** [comment]
Travis sees the exact same thing, I think it's you local branch that is out of whack.

**Comment by scshitole** [comment]
@dannyk81 
still not able to see, I deleted my local branch and created again
 sh f5pro.sh 
go version go1.10.3 darwin/amd64
Creating directory workspace
Creating subdirectories ...
Downloading code from github repo https://github.com/terraform-providers/terraform-provider-bigip
Building the provider ...
 fetching .TF file from Github ...   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   191  100   191    0     0   1030      0 --:--:-- --:--:-- --:--:--  1032
Now Change  directory path to /Users/shitole/top/src/github.com/terraform-providers/terraform-provider-bigip
Done ready to use !!!?m SJC-ML-00028512:~ shitole$ 
SJC-ML-00028512:~ shitole$ 
SJC-ML-00028512:~ shitole$ 
SJC-ML-00028512:~ shitole$ cd
SJC-ML-00028512:~ shitole$ 
SJC-ML-00028512:~ shitole$ pwd
/Users/shitole
SJC-ML-00028512:~ shitole$ cd top/src/github.com/terraform-providers/terraform-provider-bigip/
SJC-ML-00028512:terraform-provider-bigip shitole$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
SJC-ML-00028512:terraform-provider-bigip shitole$ 
SJC-ML-00028512:terraform-provider-bigip shitole$ cd bigip/
SJC-ML-00028512:bigip shitole$ go fmt *
SJC-ML-00028512:bigip shitole$ cd ..
SJC-ML-00028512:terraform-provider-bigip shitole$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
SJC-ML-00028512:terraform-provider-bigip shitole$

**Comment by scshitole** [comment]
@dannyk81  maybe I will make few changes to the files in comment section, save the file and see how it goes

**Comment by scshitole** [comment]
@dannyk81 it was GO version issue
```
 sh f5pro.sh 
go version go1.11.4 darwin/amd64
Creating directory workspace
Creating subdirectories ...
Downloading code from github repo https://github.com/terraform-providers/terraform-provider-bigip
Building the provider ...
 fetching .TF file from Github ...   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   191  100   191    0     0   3336      0 --:--:-- --:--:-- --:--:--  3350
Now Change  directory path to /Users/shitole/top/src/github.com/terraform-providers/terraform-provider-bigip
Done ready to use !!!?m SJC-ML-00028512:~ shitole$ cd /Users/shitole/top/src/github.com/terraform-providers/terraform-provider-bigip
SJC-ML-00028512:terraform-provider-bigip shitole$ cd bigip/
SJC-ML-00028512:bigip shitole$ go fmt *
resource_bigip_ltm_virtual_server.go
resource_bigip_sys_snmp_traps.go
SJC-ML-00028512:bigip shitole$ go version
go version go1.11.4 darwin/amd64
SJC-ML-00028512:bigip shitole$

**Pull request merged**
