### PR TITLE
vendor update

### PR DESCRIPTION
**Pull request by scshitole**

### CODE REVIEW

**Comment by dannyk81** [comment]
I don't think this will work now that this provided switched to Go modules.

/cc @appilon

**Comment by scshitole** [comment]
@dannyk81 does that means I dont need to do vendor update ? what are the steps?

**Comment by appilon** [comment]
We now use Go Modules for dependency management. We do however still commit the dependencies to the `vendor/` folder. If you want to update a particular dependency run

```
$ GO111MODULE=on go get github.com/some/module@version
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

This will update the dependency, pin any transitive dependencies to their correct versions, cleanup any thing possible (tidy) and copy the files into the `vendor/` folder. You will no longer use `dep`.

**Comment by scshitole** [comment]
@appilon I need to get update from https://github.com/f5devcentral/go-bigip  so it will look like this ?
```
$ GO111MODULE=on go get github.com/f5devcentral/go-bigip/module@version
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```
what is module@version be ?

**Pull request merged**
