### PR TITLE
Rework ltm policy

### PR DESCRIPTION
**Pull request by llomgui**
Hello,

import policy is now working.
update policy is fixed.

### CODE REVIEW

**Comment by papineni87** [comment]
Some of the acceptance tests are failing 
BIGIP_USER=admin BIGIP_PASSWORD=xxxx BIGIP_HOST=10.145.69.41 TF_ACC=1 go test ./bigip -v -run=TestAccBigipLtmPolicy_create

2020/01/29 02:31:26 [DEBUG] Starting graph walk: walkPlanDestroy
--- FAIL: TestAccBigipLtmPolicy_create (0.87s)
    testing.go:569: Step 0 error: errors during apply:
        
        Error: 010716de:3: Policy '/Common/Drafts/test-policy', rule 'rule6'; target 'forward' action 'select' does not support parameter of type 'name'.
        
          on /tmp/tf-test888880187/main.tf line 23:
          (source code not available)
        
        
        
        Error: 010716de:3: Policy '/Common/Drafts/http_to_https_redirect', rule 'http_to_https_redirect_rule'; target 'http-reply' action 'redirect' does not support parameter of type 'name'.
        
          on /tmp/tf-test888880187/main.tf line 39:
          (source code not available)
        
        
FAIL
FAIL	github.com/terraform-providers/terraform-provider-bigip/bigip	0.877s

Can you look into this?

**Comment by theforhad** [comment]
I would like to know the status of this? The code works when I build and run it on my end.

If it's a matter of the failed tests, both forward and http-reply do not use tm_name which is why you are receiving the "does not support parameter of type 'name'" error.

**Comment by papineni87** [comment]
Looks like tm_name should be removed in testcase and it is not been seen in the Post/Get request.

**Comment by theforhad** [comment]
@RavinderReddyF5  Any idea when will the next release be? I would like to refer to the public available provider as opposed to building it from source.

**Comment by focrensh** [comment]
We are aiming to release current updates into the provider next week.

**Pull request merged**
